In [1]:
import os 
os.environ['KERAS_BACKEND'] = 'theano'

In [2]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('facefeatures_new_model.h5')



Using Theano backend.


In [ ]:
# Loading the cascades
face_cascade = cv2.CascadeClassifier('D:\Jupyter Notebook\Real time Object Detection using Transfer learninng\haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][1]>0.5):
            name='Bhavesh'
        elif(pred[0][0]>0.5):
            name='Aparajita'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[1.0000000e+00 2.3599941e-20]]
[[0.72171205 0.27828792]]
[[1.4497782e-07 9.9999988e-01]]
[[7.820846e-16 1.000000e+00]]
[[6.748665e-13 1.000000e+00]]
[[1.7938682e-21 1.0000000e+00]]
[[4.8807078e-20 1.0000000e+00]]
[[3.4675593e-21 1.0000000e+00]]
[[8.928659e-15 1.000000e+00]]
[[4.1786825e-16 1.0000000e+00]]
[[4.595153e-14 1.000000e+00]]
[[3.1047693e-13 1.0000000e+00]]
[[1.6507835e-04 9.9983490e-01]]
[[2.0969488e-13 1.0000000e+00]]
[[9.291457e-05 9.999071e-01]]
[[0.02258222 0.97741777]]
[[9.999991e-01 8.833422e-07]]
[[1.0000000e+00 3.8156608e-10]]
[[9.9969918e-01 3.0085148e-04]]
[[0.89821005 0.10178997]]
[[7.5867494e-05 9.9992412e-01]]
[[0.8948594  0.10514062]]
[[0.22672679 0.7732732 ]]
[[3.679377e-12 1.000000e+00]]
[[8.9077868e-05 9.9991095e-01]]
[[1.000000e+00 3.164174e-18]]
[[1.0000000e+00 1.2507014e-24]]
[[1.000000e+00 2.843241e-23]]
[[1.0000000e+00 4.0915467e-17]]
[[1.0000000e+00 4.9224866e-17]]
[[4.9498653e-17 1.0000000e+00]]
[[3.4581383e-11 1.0000000e+00]]
[[7.4308925e-22 1.000000